
# The code in this file was generated by uploading 
# Canada's ECCC NIR (2025) Annex 6 PDF into Gemini, and asking it to produce
# pandas dataframes for each of the tables.

NaN = float('nan')

import numpy as np
import pandas as pd

# Data for Table A6.1-1: CO2 Emission Factors for Marketable Natural Gas (1990-2023)
# Values represent grams per cubic metre (g/m3)
data_a6_1_1 = {
    "Year": [
        "1990", "1995", "2000", "2005", "2006", "2007", "2008", "2009", "2010", "2011",
        "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"
    ],
    "Canada": [1899, 1899, 1895, 1883, 1878, 1881, 1887, 1889, 1891, 1893, 1905, 1910, 1912, 1924, 1932, 1936, 1944, 1944, 1944, 1944, 1944, 1944],
    "BC": [1926, 1926, 1918, 1898, 1896, 1901, 1906, 1900, 1902, 1900, 1899, 1909, 1912, 1939, 1941, 1955, 1966, 1966, 1966, 1966, 1966, 1966],
    "AB": [1928, 1928, 1923, 1911, 1917, 1910, 1910, 1920, 1923, 1921, 1931, 1933, 1930, 1943, 1954, 1955, 1962, 1962, 1962, 1962, 1962, 1962],
    "SK": [1829, 1829, 1839, 1864, 1855, 1857, 1863, 1861, 1860, 1866, 1874, 1875, 1878, 1881, 1897, 1900, 1920, 1920, 1920, 1920, 1920, 1920],
    "MB": [1886, 1886, 1880, 1864, 1855, 1857, 1863, 1861, 1862, 1866, 1873, 1873, 1875, 1905, 1896, 1903, 1915, 1915, 1915, 1915, 1915, 1915],
    "QC": [1887, 1887, 1880, 1864, 1854, 1858, 1865, 1865, 1868, 1870, 1882, 1884, 1882, 1911, 1907, 1915, 1926, 1926, 1926, 1926, 1926, 1926],
    "NB": [1888, 1888, 1881, 1865, 1855, 1859, 1865, 1863, 1869, 1871, 1888, 1896, 1896, 1911, 1908, 1916, 1919, 1919, 1919, 1919, 1919, 1919],
    "ON": [1901, 1901, 1884, 1864, 1855, 1858, 1864, 1862, 1865, 1869, 1880, 1887, 1887, 1912, 1915, 1910, 1921, 1921, 1921, 1921, 1921, 1921],
    "NS": [1901, 1901, 1884, 1864, 1855, 1858, 1864, 1862, 1865, 1869, 1880, 1887, 1887, 1912, 1908, 1910, 1919, 1919, 1919, 1919, 1919, 1919],
    "PE": [1901, 1901, 1884, 1864, 1855, 1858, 1864, 1862, 1865, 1869, 1880, 1887, 1887, 1912, 1908, 1910, 1919, 1919, 1919, 1919, 1919, 1919],
    "NL": [1901, 1901, 1884, 1867, 1862, 1856, 1860, 1865, 1864, 1869, 1873, 1886, 1892, 1900, 1914, 1914, 1918, 1921, 1921, 1921, 1921, 1919],
    "YT": [1901, 1901, 1900, 1898, 1896, 1901, 1906, 1900, 1902, 1900, 1899, 1909, 1912, 1939, 1941, 1955, 1966, 1966, 1966, 1966, 1966, 1966],
    "NT": [2466, 2466, 2466, 2466, 2466, 2466, 2466, 2466, 2466, 2466, 1899, 1909, 1912, 1939, 1941, 1955, 1966, 1966, 1966, 1966, 1966, 1966],
    "NU": [NaN, NaN, 1900, 1898, 1896, 1901, 1906, 1900, 1902, 1900, 1899, 1909, 1912, 1939, 1941, 1955, 1966, 1966, 1966, 1966, 1966, 1966]
}

df_a6_1_1 = pd.DataFrame(data_a6_1_1)
df_a6_1_1 = df_a6_1_1.apply(pd.to_numeric) # for years



# Data for Table A6.1-2: CO2 Emission Factors for Non-Marketable Natural Gas (1990-2023)
# Values represent grams per cubic metre (g/m3)
data_a6_1_2 = {
    "Year": [
        "1990", "1995", "2000", "2005", "2006", "2007", "2008", "2009", "2010", "2011",
        "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"
    ],
    "BC": [2162] * 22,
    "AB": [
        2080, 2080, 2080, 2080, 2080, 2080, 2080, 2080, 2054, 2062,
        2068, 2071, 2075, 2081, 2089, 2093, 2101, 2106, 2109, 2109, 2112, 2112
    ],
    "SK": [2441] * 22,
    "MB": [2401] * 22,
    "QC": ["NO"] * 22,
    "ON": [2401] * 22,
    "NB": [2401] * 22,
    "NS": [2494] * 22,
    "PE": ["NO"] * 22,
    "NL": [
        "NO", "NO", "x", 2299, 2298, 2294, 2327, 2309, 2276, 2220,
        2281, 2272, 2263, 2260, 2261, 2250, 2191, 2218, 2274, 2210, 2340, 2260
    ],
    "YT": [2401] * 22,
    "NT": [2466] * 22,
    "NU": ["NO"] * 22
}

df_a6_1_2 = pd.DataFrame(data_a6_1_2)

# Handling special notation: 'NO' (Not Occurring) and 'x' (Confidential)
# Converting to numeric and using NaN for non-numeric entries
df_a6_1_2.replace(["NO", "x"], np.nan, inplace=True)
df_a6_1_2 = df_a6_1_2.apply(pd.to_numeric)


# Data for Table A6.1-3: CH4 and N2O Emission Factors for Natural Gas
# Units are in g/m^3
data_a6_1_3 = {
    "Emission Factor Source": [
        "Electric Utilities",
        "Industrial",
        "Producer Consumption (Non-marketable)",
        "Producer Consumption (Non-marketable) - Newfoundland and Labrador",
        "Pipelines",
        "Cement",
        "Manufacturing Industries",
        "Residential, Construction, Commercial/Institutional, Agriculture"
    ],
    "CH4 (g/m3)": [0.490, 0.037, 6.4, 0.490, 1.9, 0.037, 0.037, 0.037],
    "N2O (g/m3)": [0.049, 0.033, 0.060, 0.060, 0.050, 0.034, 0.033, 0.035]
}
# N.B. there's an important note in the PDF that
# the 6.4 for "Producer Consumption (non-marketable) is not applicable in BC,
# Alberta, and Saskatchewan -- see table A6.1-4 for those
df_a6_1_3 = pd.DataFrame(data_a6_1_3)


# Data for Table A6.1-4: CH4 Emission Factors for Natural Gas Producer Consumption
# in Western Provinces (1990-2023)
# Values represent grams per cubic metre (g/m3)
data_a6_1_4 = {
    "Year": [
        "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
        "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
        "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
        "2020", "2021", "2022", "2023"
    ],
    "BC": [
        8.85, 8.85, 8.85, 8.85, 8.85, 8.85, 8.85, 8.85, 8.85, 8.85,
        8.85, 8.85, 8.87, 8.79, 9.15, 9.15, 9.15, 9.15, 9.04, 9.03,
        8.91, 8.80, 8.66, 8.59, 8.61, 8.41, 8.47, 8.39, 8.41, 8.44,
        8.59, 8.73, 8.83, 9.20
    ],
    "AB": [
        6.40, 6.40, 6.40, 6.40, 6.40, 6.40, 6.62, 6.85, 7.07, 7.29,
        7.52, 7.74, 7.96, 8.19, 8.41, 8.51, 8.50, 8.52, 8.55, 8.51,
        8.52, 8.58, 8.32, 8.33, 8.32, 8.22, 8.32, 8.39, 8.25, 8.16,
        8.23, 8.07, 8.21, 8.22
    ],
    "SK": [
        6.02, 6.42, 6.29, 5.99, 5.71, 5.54, 5.30, 5.18, 5.29, 5.19,
        5.04, 5.26, 5.44, 5.78, 4.90, 4.66, 4.77, 4.67, 4.55, 4.44,
        4.10, 3.80, 3.60, 3.44, 4.04, 3.81, 3.89, 3.89, 4.16, 4.55,
        4.82, 4.49, 4.09, 4.20
    ]
}

df_a6_1_4 = pd.DataFrame(data_a6_1_4)

# Ensure numeric types
df_a6_1_4["Year"] = pd.to_numeric(df_a6_1_4["Year"])

# Data for Table A6.1-5: Emission Factors for Natural Gas Liquids
# Units are in g/L
data_a6_1_5 = {
    "Source": [
        "Propane - Residential",
        "Propane - All Other Uses",
        "Ethane",
        "Butane"
    ],
    "CO2 (g/L)": [1515, 1515, 986, 1747],
    "CH4 (g/L)": [0.0276, 0.0246, 0.0246, 0.024],
    "N2O (g/L)": [0.1086, 0.108, 0.108, 0.108]
}

df_a6_1_5 = pd.DataFrame(data_a6_1_5)


# Data for Table A6.1-6: Emission Factors for Refined Petroleum Products
# Units are in g/L
data_a6_1_6 = {
    "Fuel Type": [
        "Light Fuel Oil", "Light Fuel Oil", "Light Fuel Oil", "Light Fuel Oil", "Light Fuel Oil",
        "Heavy Fuel Oil", "Heavy Fuel Oil", "Heavy Fuel Oil", "Heavy Fuel Oil",
        "Kerosene", "Kerosene", "Kerosene", "Kerosene", "Kerosene",
        "Diesel", "Diesel",
        "Petroleum Coke", "Still Gas", "Still Gas",
        "Motor Gasoline"
    ],
    "Sector": [
        "Electric Utilities", "Industrial", "Producer Consumption", "Residential",
        "Forestry, Construction, Public Admin, Commercial/Institutional",
        "Electric Utilities", "Industrial", "Producer Consumption",
        "Residential, Forestry, Construction, Public Admin, Commercial/Institutional",
        "Electric Utilities", "Industrial", "Producer Consumption", "Residential",
        "Forestry, Construction, Public Admin, Commercial/Institutional",
        "Refineries and Others", "Upgraders",
        "All", "Refineries and Others", "Upgraders",
        "All"
    ],
    "CO2 (g/L)": [
        2753, 2753, 2670, 2753, 2753,
        3156, 3156, 3190, 3156,
        2560, 2560, 2560, 2560, 2560,
        2681, 2681,
        NaN, NaN, NaN,
        2307
    ],
    "CH4 (g/L)": [
        0.18, 0.006, 0.006, 0.026, 0.026,
        0.034, 0.12, 0.12, 0.057,
        0.006, 0.006, 0.006, 0.026, 0.026,
        0.078, 0.078,
        0.12, NaN, .000039,
        0.100
    ],
    "N2O (g/L)": [
        0.031, 0.031, 0.031, 0.006, 0.031,
        0.064, 0.064, 0.064, 0.064,
        0.031, 0.031, 0.031, 0.006, 0.031,
        0.022, 0.022,
        NaN, .00002, 0.00002,
        0.02
    ]
}

df_a6_1_6 = pd.DataFrame(data_a6_1_6)


# Data for Table A6.1-7: CO2 Emission Factors for Petroleum Coke and Still Gas
# Petroleum Coke values are in g/L; Still Gas values are in g/m3
data_a6_1_7 = {
    "Year": [
        "1990", "1995", "2000", "2005", "2006", "2007", "2008", "2009", "2010", "2011",
        "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021",
        "2022", "2023"
    ],
    "Petroleum Coke - Upgrading Facilities (g/L)": [
        2965, 2961, 2903, 2837, 2813, 2800, 2813, 2792, 2817, 2820,
        2802, 2765, 2794, 2795, 2781, 2800, 2769, 2771, 2769, 2744,
        2729, 2717
    ],
    "Petroleum Coke - Refineries and Others (g/L)": [
        3140, 3160, 3090, 3141, 3150, 3174, 3193, 3199, 3261, 3234,
        3240, 3220, 3227, 3232, 3236, 3253, 3235, 3258, 3246, 3250,
        3199, 3254
    ],
    "Still Gas - Upgrading Facilities (g/m3)": [
        2310, 2090, 2120, 2140, 2140, 2140, 2140, 2140, 2140, 2140,
        2140, 2140, 2140, 2140, 2140, 2140, 2140, 2140, 2140, 2140,
        2140, 2140
    ],
    "Still Gas - Refineries and Others (g/m3)": [
        1740, 1800, 1680, 1707, 1741, 1749, 1690, 1711, 1825, 1818,
        1718, 1738, 1741, 1762, 1781, 1796, 1847, 1849, 1770, 1764,
        1773, 1773
    ]
}

df_a6_1_7 = pd.DataFrame(data_a6_1_7)

# Convert columns to numeric types
df_a6_1_7["Year"] = pd.to_numeric(df_a6_1_7["Year"])

# Data for Table A6.1-8: N2O Emission Factors for Petroleum Coke (1990-2023)
# Values represent grams per cubic metre (g/m3)
data_a6_1_8 = {
    "Year": [
        "1990", "1995", "2000", "2005", "2006", "2007", "2008", "2009", "2010", "2011",
        "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021",
        "2022", "2023"
    ],
    "Upgrading Facilities (g/m3)": [
        18.2, 18.9, 20.1, 19.5, 19.4, 19.3, 19.4, 19.2, 19.4, 19.4,
        19.3, 19.0, 19.2, 19.2, 19.1, 19.3, 19.1, 19.1, 19.1, 18.9,
        18.8, 18.7
    ],
    "Refineries and Others (g/m3)": [
        21.9, 22.9, 23.5, 23.0, 23.1, 23.1, 23.1, 23.2, 23.2, 23.2,
        23.4, 23.4, 23.4, 23.6, 23.5, 23.6, 23.5, 23.6, 23.6, 23.6,
        23.3, 23.6
    ]
}

df_a6_1_8 = pd.DataFrame(data_a6_1_8)

# Convert Year to numeric for analytical purposes
df_a6_1_8["Year"] = pd.to_numeric(df_a6_1_8["Year"])


# Data for Table A6.1-9: CH4 Emission Factors for Still Gas (Refineries and Others)
# Units are expressed as g/m^3 per the source document
data_a6_1_9 = {
    "Year": [
        "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
        "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
        "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
        "2020", "2021", "2022", "2023"
    ],
    "CH4 Emission Factor (g/m^3)": [
        0.033, 0.033, 0.033, 0.033, 0.033, 0.033, 0.033, 0.032, 0.031, 0.033,
        0.034, 0.034, 0.033, 0.033, 0.033, 0.032, 0.032, 0.032, 0.032, 0.032,
        0.032, 0.033, 0.031, 0.031, 0.031, 0.033, 0.032, 0.033, 0.032, 0.032,
        0.032, 0.032, 0.032, 0.032
    ]
}

df_a6_1_9 = pd.DataFrame(data_a6_1_9)

# Ensure numeric types
df_a6_1_9["Year"] = pd.to_numeric(df_a6_1_9["Year"])

# Data for Table A6.1-10: CO2 Emission Factors for Coal
# Mean Emission Factor units: kg CO2/tonne
data_a6_1_10 = {
    "Province/Territory": [
        "NL, NS, PE, QC (Prior to 2000)", "NL, NS, PE, QC (2000 onward)",
        "NB (Prior to 2010)", "NB (2010 onward)", "AB, BC, MB, ON, SK",
        "NB, NS, PE and NL", "MB", "ON", "QC, AB, BC",
        "All Prov/Terr, except SK", "SK", "QC, ON, MB", "NS, PE",
        "AB, SK, BC", "NB (2010, 2011, 2013, 2014)", "NB (2012, 2015 onward)",
        "All Prov/Terr"
    ],
    "Coal Type & Source": [
        "Canadian Bituminous (NS)", "Canadian Bituminous (AB)",
        "Canadian Bituminous (NB)", "Canadian Bituminous (AB)", "Canadian Bituminous (AB)",
        "Foreign Bituminous (Non-U.S.)", "Foreign Bituminous (U.S. PA)",
        "Foreign Bituminous (U.S. PA)", "Foreign Bituminous (U.S. PA)",
        "Lignite (SK)", "Lignite (SK)", "Sub-bituminous (Foreign)", "Sub-bituminous (Foreign)",
        "Sub-bituminous (AB)", "Sub-bituminous (Foreign)", "Sub-bituminous (Foreign)",
        "Anthracite"
    ],
    "Mean EF (kg CO2/tonne)": [
        2344, 2212, 2333, 2212, 2212, 2571, 2651, 2651, 2662,
        1463, 1463, 1865, 1743, 1775, 2189, 2352, 3097
    ],
    "EF 95% Uncertainty (lower coef)": [
        -.33, -.26, -.14, -.26, -.26, -.7, -.7, -.7, -.7,
        -.13, -.13, -.08, -.08, -.11, -.02, -.02, -.06
    ],
    "EF 95% Uncertainty (upper coef)": [
        .22, .26, .14, .26, .26, .7, .7, .7, .7,
        .13, .13, .08, .08, .11, .02, .02, .06
    ],
    "Oxidation Factor (%)": [
        98.78, 98.78, 98.78, 98.78, 98.78, 98.78, 98.78, 98.38, 98.78,
        99.92, 99.61, 99.84, 99.84, 99.36, 99.84, 99.84, 98.78
    ],
    "Moisture (wt.%)": [
        3.2, 7.7, 3.2, 7.7, 7.7, 8.3, 0.0, 0.0, 0.0,
        24, 36, 24, 24, 21, 19, 12, 0.0
    ]
}

df_a6_1_10 = pd.DataFrame(data_a6_1_10)

# Note: 'N/A' moisture values in the source document are represented as 0.0 for numeric handling.


# Data for Table A6.1-11: CO2 Emission Factors for Coke Oven Gas and Coke
data_a6_1_11 = {
    "Coal Product - Fuel Type": [
        "Coke Oven Gas",
        "Coke"
    ],
    "Emission Factor": [
        687,
        3173
    ],
    "Units": [
        "g/m³",
        "g/kg"
    ],
    "Data Source": [
        "McCann (2000)",
        "CRA (2014)"
    ]
}

df_a6_1_11 = pd.DataFrame(data_a6_1_11)



# Data for Table A6.1-12: CH4 and N2O Emission Factors for Coal, Coke and Coke Oven Gas
data_a6_1_12 = {
    "Source": [
        "Coal - Electric Utilities",
        "Coal - Industry and Heat & Steam Plants",
        "Coal - Residential, Public Administration",
        "Coke",
        "Coke Oven Gas"
    ],
    "CH4 Emission Factor": [
        0.02, 0.03, 4.00, 0.03, 0.04
    ],
    "N2O Emission Factor": [
        0.03, 0.02, 0.02, 0.02, 0.04
    ],
    "Units": [
        "g/kg", "g/kg", "g/kg", "g/kg", "g/m3"
    ]
}

df_a6_1_12 = pd.DataFrame(data_a6_1_12)


# Data for Table A6.1-13: Provincially Weighted Coal Mining Fugitive Emission Factors
# Units: t CH4 / kt coal mined
data_a6_1_13 = {
    "Year": [
        "1990", "1995", "2000", "2005", "2006", "2007", "2008", "2009", "2010",
        "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019",
        "2020", "2021", "2022", "2023"
    ],
    "Bituminous - AB": [
        0.58, 0.58, 0.59, 0.51, 0.48, 0.47, 0.47, 0.43, 0.44, 0.42,
        0.45, 0.46, 0.52, 0.55, "C", "C", 0.51, 0.47, 0.36, "C",
        0.31, 0.31
    ],
    "Bituminous - BC": [
        0.82, 0.82, 0.82, 0.87, 0.86, 0.87, 0.85, 0.85, 0.86, 0.84,
        0.85, 0.84, 0.84, 0.86, 0.87, 0.86, 0.92, 0.93, 0.93, 0.93,
        0.92, 0.92
    ],
    "Bituminous - NS": ["C", 0.07, 0.07, 0.07, 0.07] + ["C"] * 17,
    "Subbituminous - AB": [
        0.18, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.20, 0.20, 0.21,
        0.21, 0.22, 0.20, 0.20, 0.21, 0.22, 0.23, 0.24, 0.21, 0.15,
        0.15, 0.15
    ],
    "Lignite - SK": [
        0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07,
        0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07,
        0.07, 0.07
    ]
}

df_a6_1_13 = pd.DataFrame(data_a6_1_13)

# Handling "C" for Confidential data by converting to NaN for numeric analysis
df_a6_1_13.replace("C", np.nan, inplace=True)

# Convert all columns except 'Year' to numeric
cols = df_a6_1_13.columns.drop("Year")
df_a6_1_13[cols] = df_a6_1_13[cols].apply(pd.to_numeric)



# Data for Table A6.1-14: Emission Factors for Alternative Fuels (Cement Industry)
# Units: kg/GJ
data_a6_1_14 = {
    "Year": [
        "1990", "1995", "2000", "2005", "2006", "2007", "2008", "2009", "2010", "2011",
        "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021",
        "2022", "2023"
    ],
    "CO2 (kg/GJ)": [
        78.8, 77.6, 77.6, 81.1, 79.4, 80.1, 79.5, 78.2, 79.3, 79.1,
        79.1, 79.1, 79.1, 79.1, 79.1, 88.7, 83.0, 88.9, 68.5, 81.7,
        75.9, 77.0
    ],
    "CH4 (kg/GJ)": [0.03] * 22,
    "N2O (kg/GJ)": [0.004] * 22
}

df_a6_1_14 = pd.DataFrame(data_a6_1_14)

# Ensure numeric types
df_a6_1_14["Year"] = pd.to_numeric(df_a6_1_14["Year"])


import numpy as np

# Data structure representing Table A6.1-15 from the National Inventory Report
# Columns: Mode, Category, Sub-Category/Technology, Fuel Type, CO2 (g/L), CH4 (g/L), N2O (g/L)
data_a6_1_15 = [
    # Road Transport - Gasoline Vehicles - Light-duty Gasoline Vehicles (LDGVs)
    ("Road Transport", "Light-duty Gasoline Vehicles (LDGVs)", "Tier 3", "Gasoline", 2307.3, 0.111, 0.007),
    ("Road Transport", "Light-duty Gasoline Vehicles (LDGVs)", "Tier 2", "Gasoline", 2307.3, 0.14, 0.022),
    ("Road Transport", "Light-duty Gasoline Vehicles (LDGVs)", "Tier 1", "Gasoline", 2307.3, 0.23, 0.47),
    ("Road Transport", "Light-duty Gasoline Vehicles (LDGVs)", "Tier 0", "Gasoline", 2307.3, 0.32, 0.66),
    ("Road Transport", "Light-duty Gasoline Vehicles (LDGVs)", "Oxidation Catalyst", "Gasoline", 2307.3, 0.52, 0.20),
    ("Road Transport", "Light-duty Gasoline Vehicles (LDGVs)", "Non-catalytic Controlled", "Gasoline", 2307.3, 0.46, 0.028),

    # Road Transport - Gasoline Vehicles - Light-duty Gasoline Trucks (LDGTs)
    ("Road Transport", "Light-duty Gasoline Trucks (LDGTs)", "Tier 3", "Gasoline", 2307.3, 0.111, 0.007),
    ("Road Transport", "Light-duty Gasoline Trucks (LDGTs)", "Tier 2", "Gasoline", 2307.3, 0.14, 0.022),
    ("Road Transport", "Light-duty Gasoline Trucks (LDGTs)", "Tier 1", "Gasoline", 2307.3, 0.24, 0.58),
    ("Road Transport", "Light-duty Gasoline Trucks (LDGTs)", "Tier 0", "Gasoline", 2307.3, 0.21, 0.66),
    ("Road Transport", "Light-duty Gasoline Trucks (LDGTs)", "Oxidation Catalyst", "Gasoline", 2307.3, 0.43, 0.20),
    ("Road Transport", "Light-duty Gasoline Trucks (LDGTs)", "Non-catalytic Controlled", "Gasoline", 2307.3, 0.56, 0.028),

    # Road Transport - Gasoline Vehicles - Heavy-duty Gasoline Vehicles (HDGVs)
    ("Road Transport", "Heavy-duty Gasoline Vehicles (HDGVs)", "Three-way Catalyst", "Gasoline", 2307.3, 0.068, 0.20),
    ("Road Transport", "Heavy-duty Gasoline Vehicles (HDGVs)", "Non-catalytic Controlled", "Gasoline", 2307.3, 0.29, 0.047),
    ("Road Transport", "Heavy-duty Gasoline Vehicles (HDGVs)", "Uncontrolled", "Gasoline", 2307.3, 0.49, 0.084),

    # Road Transport - Gasoline Vehicles - Motorcycles
    ("Road Transport", "Motorcycles", "Non-catalytic Controlled", "Gasoline", 2307.3, 0.77, 0.041),
    ("Road Transport", "Motorcycles", "Uncontrolled", "Gasoline", 2307.3, 2.3, 0.048),

    # Road Transport - Diesel Vehicles - Light-duty Diesel Vehicles (LDDVs)
    ("Road Transport", "Light-duty Diesel Vehicles (LDDVs)", "Advanced Control", "Diesel", 2680.5, 0.051, 0.22),
    ("Road Transport", "Light-duty Diesel Vehicles (LDDVs)", "Moderate Control", "Diesel", 2680.5, 0.068, 0.21),
    ("Road Transport", "Light-duty Diesel Vehicles (LDDVs)", "Uncontrolled", "Diesel", 2680.5, 0.10, 0.16),

    # Road Transport - Diesel Vehicles - Light-duty Diesel Trucks (LDDTs)
    ("Road Transport", "Light-duty Diesel Trucks (LDDTs)", "Advanced Control", "Diesel", 2680.5, 0.068, 0.22),
    ("Road Transport", "Light-duty Diesel Trucks (LDDTs)", "Moderate Control", "Diesel", 2680.5, 0.068, 0.21),
    ("Road Transport", "Light-duty Diesel Trucks (LDDTs)", "Uncontrolled", "Diesel", 2680.5, 0.085, 0.16),

    # Road Transport - Diesel Vehicles - Heavy-duty Diesel Vehicles (HDDVs)
    ("Road Transport", "Heavy-duty Diesel Vehicles (HDDVs)", "Advanced Control", "Diesel", 2680.5, 0.11, 0.151),
    ("Road Transport", "Heavy-duty Diesel Vehicles (HDDVs)", "Moderate Control", "Diesel", 2680.5, 0.14, 0.082),
    ("Road Transport", "Heavy-duty Diesel Vehicles (HDDVs)", "Uncontrolled", "Diesel", 2680.5, 0.151, 0.075),

    # Road Transport - Other
    ("Road Transport", "Natural Gas Vehicles", "N/A", "Natural Gas", 1.9, 0.0088, 0.00006),
    ("Road Transport", "Propane Vehicles", "N/A", "Propane", 1515, 0.64, 0.028),

    # Off-road
    ("Off-road", "Gasoline 2-stroke", "N/A", "Gasoline", 2307.3, 10.56, 0.0139),
    ("Off-road", "Gasoline 4-stroke", "N/A", "Gasoline", 2307.3, 5.08, 0.064),
    ("Off-road", "Diesel < 19kW", "N/A", "Diesel", 2680.5, 0.073, 0.022),
    ("Off-road", "Diesel >= 19kW", "Tier 1-3", "Diesel", 2680.5, 0.073, 0.022),
    ("Off-road", "Diesel >= 19kW", "Tier 4", "Diesel", 2680.5, 0.073, 0.227),
    ("Off-road", "Lubricating Oil 2-stroke", "N/A", "Lubricating Oil", 2705.09, 12.699, 0.016),
    ("Off-road", "Natural Gas", "N/A", "Natural Gas", 1.9, 0.0088, 0.00006),
    ("Off-road", "Propane", "N/A", "Propane", 1515, 0.64, 0.087),

    # Railways
    ("Railways", "Diesel Train", "N/A", "Diesel", 2680.5, 0.149, 1.029),

    # Marine
    ("Marine", "Gasoline", "N/A", "Gasoline", 2307.3, 0.21931, 0.06266),
    ("Marine", "Diesel", "N/A", "Diesel", 2680.5, 0.25193, 0.07198),
    ("Marine", "Light Fuel Oil", "N/A", "Light Fuel Oil", 2753, 0.2555, 0.073),
    ("Marine", "Heavy Fuel Oil", "N/A", "Heavy Fuel Oil", 3156, 0.2856, 0.0816),
    ("Marine", "Kerosene", "N/A", "Kerosene", 2559.7, 0.2471, 0.0706),

    # Aviation
    ("Aviation", "Aviation Gasoline", "N/A", "Aviation Gasoline", 2325.4, 2.19, 0.23),
    ("Aviation", "Aviation Turbo Fuel", "N/A", "Aviation Turbo Fuel", 2559.7, 0.018, 0.0711),

    # Renewable Fuels
    ("Renewable Fuels", "Ethanol", "N/A", "Ethanol", 1508.04, np.nan, np.nan),
    ("Renewable Fuels", "Biodiesel", "N/A", "Biodiesel", 2472.2, np.nan, np.nan),
]

columns_a6_1_15 = ["Mode", "Category", "Technology_Tier", "Fuel_Type", "CO2_EF_g_L", "CH4_EF_g_L", "N2O_EF_g_L"]
df_a6_1_15 = pd.DataFrame(data_a6_1_15, columns=columns_a6_1_15)

# Note on Renewables: CH4 and N2O factors for Ethanol/Biodiesel depend on the specific vehicle/mode
# and are generally assumed to be the same as the gasoline/diesel equivalent (see Table Notes).


# Table A6.5–1 Default Parameter Values Used in Harvested Wood Products
# Analysis
data_a6_5_1 = {
    'Description': [
        'Bark expansion factor, Softwoods',
        'Bark expansion factor, Hardwoods',
        'Bark expansion factor, Mixedwoods',
        'C content of wood'],
    'Units': [
        'dimensionless',
        'dimensionless',
        'dimensionless',
        'tonnes C per od tonne'],
    'Value': [1.11, 1.15, 1.13, .5],
}

# Table A6.5–2 Wood Densities of Commodities
data_a6_5_2 = {
    'Country': ['Canada'] * 5,
    'Description': [
        'Species-weighted average density, Roundwood',
        'Species-weighted average density, Sawnwood',
        'Species-weighted average density, Other industrial roundwood',
        'Species-weighted average density, Panels',
        'Species-weighted average density, Bioenergy',
    ],
    'Units': ['od tonne per m3'] * 5,
    'Value': [
        .386,
        .481,
        .583,
        .643,
        .523,
    ],
}


# Table A6.5–3 Half-Life Parameters (Years) of Harvested Wood Products In-use
data_a6_5_3 = {
    'Countries': ['Canada'] * 4 + ['U.S.'] * 4 + ['Rest of World'] * 4,
    'Description': ['Sawnwood', 'Wood panels', 'Pulp and paper', 'Other industrial roundwood'] * 4,
    'Values': [35, 25, 2, 35, 40, 27.04, 3.25, 40, 35, 25, 2, 35],
}
