name: Clean up Review App on Fly.io

on:
  pull_request:
    types: [closed]

  shutdown_app:
    if: github.repository == 'jaberg/planzero'
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}
      #
    # Deploying apps with this "review" environment allows the URL for the app to be displayed in the PR UI.
    # Feel free to change the name of this environment.
    environment:
      name: Fly Review
      # The script in the `deploy` sets the URL output for each review app.
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        env:
          FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"
        with:
          config: fly_gh.toml

