name: Inference

on: push

jobs:
  estimate_static_normal_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache Static Normals
        id: cache-static-normals
        uses: actions/cache@v5
        with:
          path: ~/foo
          key: foo-v1

      - name: Populate the cache
        if: ${{ steps.cache-static-normals.outputs.cache-hit != 'true'}}
        run: date >> ~/foo
